# Generated by Django 6.0.6 on 2026-06-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant.', max_length=255)),
                ('cuisine', models.CharField(help_text='Cuisine type served.', max_length=255)),
                ('rating', models.FloatField(help_text='Rating from 0.0 to 5.0.')),
            ],
        ),
    ]
