# Generated by Django 6.0.6 on 2026-06-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant.', max_length=255)),
                ('cuisine', models.CharField(help_text='Cuisine type served (e.g. Italian, Indian).', max_length=255)),
                ('location', models.CharField(help_text='Location/City of the restaurant.', max_length=255)),
            ],
        ),
    ]
