# Generated by Django 6.0.6 on 2026-06-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the restaurant.', max_length=255)),
                ('cuisine', models.CharField(help_text='The type of cuisine served (e.g., Italian, Chinese).', max_length=255)),
            ],
        ),
    ]
